### ISSUE TITLE
[BUG] Latest repo shows an error when running `npm run examples`

### ISSUE THREAD

**Issue by sravyam28** [EasyEyes/threshold#74]
**Describe the bug**
Not able to run demoExperiment using latest repo

**To Reproduce**
1. Clone the git repository
2. Run npm install
3. npm run build
4. npm run examples

Below error seen on npm run examples command
```
Error: ENOENT: no such file or directory, scandir 'folders/'
    at readdirSync (node:fs:1438:3)
    at copyFolder (/home/sravyam/meta_workspace/latest_sep1/threshold/examples/buildExamples.ts:171:31)
    at /home/sravyam/meta_workspace/latest_sep1/threshold/examples/buildExamples.ts:132:7
    at /home/sravyam/meta_workspace/latest_sep1/threshold/preprocess/main.ts:403:5
    at step (/home/sravyam/meta_workspace/latest_sep1/threshold/preprocess/main.ts:33:23)
    at Object.next (/home/sravyam/meta_workspace/latest_sep1/threshold/preprocess/main.ts:14:53)
    at /home/sravyam/meta_workspace/latest_sep1/threshold/preprocess/main.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/sravyam/meta_workspace/latest_sep1/threshold/preprocess/main.ts:4:12)
    at prepareExperimentFileForThreshold (/home/sravyam/meta_workspace/latest_sep1/threshold/preprocess/main.ts:89:20) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'folders/'
}
```
**Expected behavior**

Demo Experiment to run as expected with clean clone from latest repo

**Screenshots**

![Screenshot from 2023-09-01 11-19-28](https://github.com/EasyEyes/threshold/assets/117389237/4db3cef9-474b-4fdd-9c75-3503bbb0631e)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sravyam28** [comment]
Thanks, Adding the directory ```folders``` in examples fixed the issue
Yes, I did run both the above commands when I encountered the issue before

**Comment by denispelli** [comment]
https://trello.com/c/TUTbQP9f
